version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    container_name: ai-image-analyzer-frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: ai-image-analyzer-backend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3001"